"""job foreign key and index

Revision ID: 774ee0a63b39
Revises: 50c3796264e9
Create Date: 2026-07-29 14:28:39.875805

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "774ee0a63b39"
down_revision: str | Sequence[str] | None = "50c3796264e9"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("jobs", schema=None) as batch_op:
        batch_op.create_index("ix_jobs_doc_sha", ["doc_sha"], unique=False)
        batch_op.create_foreign_key(
            "fk_jobs_doc_sha_documents", "documents", ["doc_sha"], ["sha256"]
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("jobs", schema=None) as batch_op:
        batch_op.drop_constraint("fk_jobs_doc_sha_documents", type_="foreignkey")
        batch_op.drop_index("ix_jobs_doc_sha")

    # ### end Alembic commands ###
